### ISSUE TITLE
Nginx 1.3.12

### ISSUE THREAD

**Issue by MTecknology** [vkholodkov/nginx-upload-module#45]
It seems that this module no longer works on nginx 1.3.12.

    gcc -c -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wall -DFORTIFY_SOURCE=2 -fstack-protector -D_FORTIFY_SOURCE=2  -DNDK_SET_VAR  -I src/core -I src/event -I src/event/modules -I src/os/unix -I /build/buildd/nginx-1.3.12/debian/modules/nginx-development-kit/objs -I objs/addon/ndk -I /build/buildd/nginx-1.3.12/debian/modules/nginx-http-push/src -I /usr/include/lua5.1 -I /build/buildd/nginx-1.3.12/debian/modules/nginx-lua/src/api -I /usr/include/libxml2 -I objs -I src/http -I src/http/modules -I src/http/modules/perl -I /build/buildd/nginx-1.3.12/debian/modules/nginx-development-kit/src -I src/mail \
                    -o objs/addon/nginx-upload-module/ngx_http_upload_module.o \
                    /build/buildd/nginx-1.3.12/debian/modules/nginx-upload-module/ngx_http_upload_module.c
    /build/buildd/nginx-1.3.12/debian/modules/nginx-upload-module/ngx_http_upload_module.c: In function 'ngx_http_upload_merge_ranges':
    /build/buildd/nginx-1.3.12/debian/modules/nginx-upload-module/ngx_http_upload_module.c:1681:18: warning: variable 'result' set but not used [-Wunused-but-set-variable]
    /build/buildd/nginx-1.3.12/debian/modules/nginx-upload-module/ngx_http_upload_module.c: In function 'ngx_http_read_upload_client_request_body':
    /build/buildd/nginx-1.3.12/debian/modules/nginx-upload-module/ngx_http_upload_module.c:2628:15: error: 'ngx_http_request_body_t' has no member named 'to_write'
    /build/buildd/nginx-1.3.12/debian/modules/nginx-upload-module/ngx_http_upload_module.c:2687:7: error: 'ngx_http_request_body_t' has no member named 'to_write'
    /build/buildd/nginx-1.3.12/debian/modules/nginx-upload-module/ngx_http_upload_module.c: In function 'ngx_http_do_read_upload_client_request_body':
    /build/buildd/nginx-1.3.12/debian/modules/nginx-upload-module/ngx_http_upload_module.c:2769:57: error: 'ngx_http_request_body_t' has no member named 'to_write'
    /build/buildd/nginx-1.3.12/debian/modules/nginx-upload-module/ngx_http_upload_module.c:2785:19: error: 'ngx_http_request_body_t' has no member named 'to_write'
    /build/buildd/nginx-1.3.12/debian/modules/nginx-upload-module/ngx_http_upload_module.c:2877:45: error: 'ngx_http_request_body_t' has no member named 'to_write'
    make[2]: *** [objs/addon/nginx-upload-module/ngx_http_upload_module.o] Error 1
