### ISSUE TITLE
Cannot build with nginx-1.11.2

### ISSUE THREAD

**Issue by cbj4074** [vkholodkov/nginx-upload-module#79]
This error is back again as of `nginx-1.11.2`:

```
../nginx-upload-module-2.2/ngx_http_upload_module.c:14:17: fatal error: md5.h: No such file or directory
compilation terminated.
objs/Makefile:1196: recipe for target 'objs/addon/nginx-upload-module-2.2/ngx_http_upload_module.o' failed
make[1]: *** [objs/addon/nginx-upload-module-2.2/ngx_http_upload_module.o] Error 1
make[1]: Leaving directory '/root/nginx-build/nginx-1.11.2'
Makefile:8: recipe for target 'build' failed
make: *** [build] Error 2
```

Curiously, the exact same configure options that fail with `nginx-1.11.2` "work fine" with `nginx-1.10.1`, in the sense that the build process seems to succeed, but then I get "unknown directive upload_progress".

I've gone back through some of the stable builds that I've used in the past, and this plugin still compiles and works with `nginx-1.8.1`. So, it seems something in nginx has changed and needs to be updated in the plugin.

Thanks!

**Comment by igreenfield** [comment]
@cbj4074 Did you find solution?

**Comment by cbj4074** [comment]
@igreenfield No :( Not yet.

**Comment by dup2** [comment]
A wild guess (from the nginx changelog) and not tested

     Change: now nginx always uses internal MD5 and SHA1 implementations

Maybe you could change the include to
    
     include "ngx_md5.h"

and the same for sha1.

**Comment by ktonini** [comment]
That got it past the initial error, but it appears that ngx_md5.h and md5.h still differ to much-

`error: unknown type name ‘MD5_CTX’
     MD5_CTX     md5;`
`error: ‘MD5_DIGEST_LENGTH’ undeclared here (not in a function)
     u_char      md5_digest[MD5_DIGEST_LENGTH * 2];`

etc.

**Comment by deweydb** [comment]
Is there an alternative to this module? it seems like development is pretty much dead.

**Comment by ktonini** [comment]
Not that in the form of an nginx module, at least that I could find.  But there's other solutions like [this](https://scribie.com/blog/2014/09/chunked-upload-with-nginx-and-nodejs/) and there's another jQuery one floating around.

**Comment by Austinb** [comment]
After looking at the changeset for 1.11.2 here: https://trac.nginx.org/nginx/changeset/6603/nginx (or https://github.com/nginx/nginx/commit/c60b61a290960c1411d4da34d7f9265a43fd831b) and scroll down to src/core/ngx_md5.h you can see that the definition for MD5_CTX was removed.  So it is trying to find something that does not exist anymore which is why the make errors out. Also the SHA_CTX typedef was removed in the sha1.h file in the same commit. 

After messing around (I have little experience in C) I deduced that the openssl libs that this module is relying on are missing because of the changes to the core of nginx removing these references (maybe a bug on nginx's part?).  There are also definitions for sha265 and other higher encryption functions that nginx does not support in its core such as 'SHA256_CTX'.  So changing the top section of the file and removing all of the if/then statements and including everything I got the module to compile without error.  Does it work the same?  I have no idea.  I have not had a chance to test it yet.  Please test and let me know.   Also I am sure the changes can be optimized so please do so.  

Will put up a pull request momentarily.

**Comment by cbj4074** [comment]
@Austinb Nice! I will give this a try in the next day or two and report back. Thank you!

**Comment by tkoenig** [comment]
@Austinb @cbj4074 you do not need to include both the openssl and ngx implementations afaik.

I tested the md5 and sha1 generation with the following adaptation:
```
#include <openssl/md5.h>

#define  MD5Init    MD5_Init
#define  MD5Update  MD5_Update
#define  MD5Final   MD5_Final

#include <openssl/sha.h>
```

I'm not sure if you need to explicitly specify an openssl library but I compiled with the `--with-openssl=../openssl-1.0.2h` configuration.

**Comment by Austinb** [comment]
@tkoenig Thanks for the info.  I just ran a quick one without the ngx_* header files and it compiled fine.  You shouldn't need to --with-openssl unless you need to specify so configure can locate it.  My configure does not include that switch. 

I ran some quick upload tests a few days ago and it appears to work the same.  Has anyone else tested the actual upload side in 1.11.2?

**Comment by tkoenig** [comment]
@Austinb Thanks for the info. Uploads work fine for me with 1.11.2 and the upload module (partial & non-partial uploads).

**Comment by Austinb** [comment]
Updated pull request #80 not that it will make much difference since there a long standing patches yet to be merged in.

**Comment by WeOggy** [comment]
no solution yet? :(

**Comment by Austinb** [comment]
@WeOggy I have a branch that has both the #77 and #80 patches in it.  Not sure #77 is needed anymore as of 1.11.5.

You can pull https://github.com/Austinb/nginx-upload-module in place of the existing path but make sure you change to branch 2.2.  I kept the layout the same. 

As far as this repo I am not sure the author is even checking up on it anymore.  Last merge was 2014 so sadly we maybe out of luck keeping this repo up to date.

**Comment by ronny332** [comment]
Just as small addition:

with nginx 1.12.0 compiling again fails. It looks like the whole openssl/crypto support was dropped.
It only compiles if you add "-lcrypto" to the previously failed linker command (of cause this is normal than a bad work around).

**Comment by duanyong** [comment]
I have the same problem，used this https://github.com/Austinb/nginx-upload-module fixed it.

under the configuration info:

Configuration summary
  + using threads
  + using system PCRE library
  + using system OpenSSL library
  + using system zlib library

make info:
make[1]: Leaving directory '/tmp/nginx-1.13.1'

**Comment by cbj4074** [comment]
This appears to be fixed via https://github.com/vkholodkov/nginx-upload-module/pull/88

For the sake of thoroughness, it's necessary to build using the 2.255 tag from  https://github.com/vkholodkov/nginx-upload-module/tree/2.255 . I don't believe this fix to have been merged into the 2.2 branch as yet.

THANK YOU to all involved!
